// resources/js/Pages/Sample.jsx
import React, {useState} from "react";
import {Link, useForm} from '@inertiajs/react'
import {route} from 'ziggy-js';

const Sample = ({ users }) => {

  const { data, setData, post, processing, errors, reset } = useForm({
    name: '',
    email: '',
    password: '',
  })

  function formSubmit(e) {
    e.preventDefault();
    post('/');
    reset();
  }

  function deleteUser(userId) {
    post(route('userDelete', {user: userId}));
  }

  return (
    <>
      <Link href={route('login')}>Login</Link>

      {processing && <h1 className="text-2xl font-bold">Loading...</h1>}
      <form method="POST" onSubmit={formSubmit}>
        <input type="text" value={data.name} onChange={(e) => setData('name', e.target.value)} name="name"/>
        <input type="text" value={data.email} onChange={(e) => setData('email', e.target.value)} name="email"/>
        <input type="text" value={data.password} onChange={(e) => setData('password', e.target.value)} name="password"/>

        <button>Submit</button>
      </form>

      <ul>
        {users.map((user, index) => (
          <li onClick={() => deleteUser(user.id)} key={index}>{user.name}</li>
        ))}
      </ul>
    </>
  );
};

export default Sample;

// resources/js/Pages/Sample.svelte
<script>
  import {Link, router, useForm} from '@inertiajs/svelte'
  import { route } from 'ziggy-js';

  const form = useForm({
    name: null,
    email: null,
    password: null,
  });

  let { users } = $props();

  function submit(e) {
    e.preventDefault();

    $form.post(route('register'));
    $form.reset();
  }

  function deleteUser(userId) {
    router.delete(route('userDelete', userId));
  }
</script>

<form onsubmit={submit} class="flex-col gap-2">
  <input type="text" name="name" bind:value={$form.name} />
  {#if $form.errors.name}
    <p class="text-xs text-red-400">{$form.errors.name}</p>
  {/if}
  <input type="email" name="email" bind:value={$form.email} />
  {#if $form.errors.email}
    <p class="text-xs text-red-400">{$form.errors.email}</p>
  {/if}
  <input type="password" name="password" bind:value={$form.password} />
  {#if $form.errors.password}
    <p class="text-xs text-red-400">{$form.errors.password}</p>
  {/if}

  <button disabled={$form.processing}>Register</button>
</form>

<Link href={route('logout')}>Logout</Link>

<ul>
{#each users as user}
  <li>{user.name} - <button onclick={() => deleteUser(user.id)}>DELETE</button></li>
{/each}
</ul>
